const facts = [
  "A dinosaur called the Pegomastax is one of the weirdest dinosaurs known. Described as a cross between a parrot and porcupine, it had a beak with teeth that sharpened themselves against each other.",
  "In the 1993 movie, Jurassic Park, there is only 15 minutes of dinosaur footage: 6 minutes of CGI and 9 minutes of animatronics.",
  "One of the weirdest dinosaurs is the Suzhousaurus. Looking like a giant rat, this odd dinosaur also had a furry body, which suggests it is a distant ancestor of the giant ground sloth.",
  "People have only been on Earth about 2.5 million years. Dinosaurs lived on Earth for about 160 million years, which is about 64 times longer than people been around.",
  'The name "Velociraptor" means speedy thief.',
  'In 2015, scientist discovered a new dinosaur species. They nicknamed it "Hellboy" because the stubby horns above its eyes looked like the comic book character of the same name. They also had a "hellish" time excavating it from hard rock.',
  "The only known example of the giant sauropod Seismosaurus appears to have choked to death on a stone it was trying to swallow to use as a gastrolith.",
  "A T-rex bite was more than twice as powerful as a lion's bite.",
  "Dinosaur skulls had large holes or “windows” that made their skulls lighter. Some of the largest skulls were as long as a car.",
  "Dinosaurs lived on all the continents, including Antarctica.",
  "Colorado’s nickname is the Stegosaurus State. The first ever Stegosaurus skeleton was found near Morrison, Colorado.",
  "Some of the biggest plant eaters had to eat as much as a ton of food a day. This is similar to eating a bus-sized pile of vegetation every day.",
  "Though mosasaurs, ichthyosaurs, pterosaurs, plesiosaurs, and Dimetrodon are commonly believed to be dinosaurs, they are not technically dinosaurs. The term “dinosaur” refers to just land-dwelling reptiles that have a specific hip structure, among other traits.",
  "While many people think dinosaurs were massive, dinosaurs were usually human sized or smaller. Scientists believe that the larger bones were just easier to be fossilized.",
  "Meat-eating dinosaurs are known as theropods, which means “beast-footed,” because they had sharp, hooked claws on their toes. In contrast, plant-eating dinosaurs tended to have blunt hooves or toenails.",
  "Some dinosaurs’ tails were over 45 feet long. Most dinosaurs had long tails that helped them to keep their balance when running.",
  "Dinosaurs were reptiles that lived on Earth from about 230 million years ago to about 65 million years ago.",
  "The earliest named dinosaur found so far is the Eoraptor (“dawn stealer”). It was so named because it lived at the dawn of the Dinosaur Age. It was a meat eater about the size of a German shepherd. The first Eoraptor skeleton was discovered in Argentina in 1991. However, another dinosaur has recently been found in Madagascar that dates as being 230 million years old. It has not been named yet.",
  "Dinosaurs are divided into two groups by the structure of their hipbones. In the hips of saurischian, or lizard hipped, dinosaurs, one of the bones pointed forward. In the hips of ornithischian, or bird-hipped, dinosaurs, all the bones pointed backward. Ironically, scientists believe that birds evolved from lizard-hipped dinosaurs, not bird-hipped dinosaurs.",
  "The word “dinosaur” was coined by British paleontologist Richard Owen in 1842. It is Greek, meaning “terrible lizard.” Rather than implying that dinosaurs were fearsome, Owen used the term to refer to their majesty and size.",
  "The first dinosaurs that appeared during the Triassic Period 230 million years ago were small and lightweight. Bigger dinosaurs such as Brachiosaurus and Triceratops appeared during the Jurassic and Cretaceous periods.",
  "The dinosaur with the longest name is Micropachycephalosaurus (“small thick-headed lizard”). Its fossils are usually found in China.",
  "Dinosaurs dominated Earth for over 165 million years. Humans have been around for only 2 million years.",
  "Many scientists believe that a massive meteorite hit the Yucatan Peninsula of Mexico 65.5 million years ago and caused the extinction of the dinosaurs as well as the pterosaurs and plesiosaurs. The 112-mile-wide crater was caused by a rock 6 miles in diameter. It would have hit Earth’s crust with immense force, sending shockwaves around the world. No land animal heavier than a large dog survived. However, animals such as sharks, jellyfish, fish, scorpions, birds, insects, snakes, turtles, lizards, and crocodiles survived.",
  "No one knows exactly how long a dinosaur’s lifespan was. Some scientists speculate some dinosaurs lived for as long as 200 years.",
  "Scientists estimate that there were over 1,000 different species of non-avian dinosaurs and over 500 distinct genera. They speculate there are many still undiscovered dinosaurs and that there may be as many as 1,850 genera.",
  "The mass extinction of the dinosaurs and other animals that took place 65.5 million years ago is known as the Cretaceous-Tertiary extinction event, or the K-T event. Scientists have several theories for this extensive die-off. One theory proposes that small mammals ate dinosaur eggs until the population became unsustainable. Other scientists believe the cause was dinosaurs’ bodies becoming too big for their small brains, a great plaque decimating the population, starvation, or climate change.",
  "Mary Anning (1799-1847) was one of the most famous of all fossil hunters. However, she was never taken as seriously as she should have been because she was a woman from a poor background whereas most scientists were men from wealthy families.",
  "Scientists believe that some dinosaurs were cold blooded, others warm blooded, and still others not fully one or the other. Small meat eaters may have been warm blooded. Plant eaters who were not as active were probably cold blooded. A warm-blooded animal needs about 10 times more food than a cold-blooded animal the same size.",
  "Explorer Roy Chapman Andrews found the first dinosaur nest known to science in 1923 in the Gobi Desert of Mongolia. Before he found the nest, scientists were unsure how dinosaur babies were born.",
  "The largest dinosaur eggs were as large as basketballs. The bigger the egg, the thicker the shell. So if the eggs had been larger, dinosaur babies probably would not have been able to get out.",
  "The first dinosaurs were carnivores, or meat eaters. Later herbivores (plant eaters) and omnivores (both meat and plant eaters) appeared.",
  "Triceratops had the biggest skull with a solid shield than any other dinosaur. It was up to 6½ feet (2 m) long, with a bony shield over its neck.",
  'In the original Jurassic Park, Michael Crichton wanted John Hammond, the park overseer, to be a dark "Walt Disney."',
  "Most dinosaurs were vegetarians.",
  "The Stegosaurus has the smallest brain for its body size of any known dinosaur. Its body was the size of a van, but its brain was the size of a walnut.",
  "One tribe of Native Americans—the Peigan people of Alberta, Canada—thought dinosaur skeletons belonged to “the fathers of buffaloes.” Englishmen 300 hundred years ago believed dinosaur bones came from an elephant or even giant humans.",
  "The first recorded description of a possible dinosaur bone discovery dates back to 3,500 years ago in China. At the time, people did not know about dinosaurs, so they thought their discovery, which was some dinosaur teeth, belonged to dragons.",
  "Measuring 50 feet, Liopleurodon was the biggest aquatic reptile, half the size of the blue whale.",
  "The blue whale is bigger than any dinosaur at 108 feet (33 m).",
  "Most meat-eating dinosaurs had bones filled with air. Though their bones were huge, they weren’t as heavy as they looked. Birds have the same kind of hollow bones.",
  "Baby Mussaurus (“mouse lizard”) are the smallest dinosaur skeletons ever found. They would fit inside a shopping bag.",
  "Small meat eaters were most likely the smartest type of dinosaurs.",
  "Humans’ eyes face forward so that they can see in 3D. Plant-eating dinosaurs, like the Triceratops, had eyes looking out to each side, so they could watch for danger while they fed.",
  "A newborn human baby has a bigger brain than most adult dinosaurs had. Whales and dolphins have the biggest brains of all living animals.",
  "Most meat eaters walked on two feet. This made them faster and left their hands free to grab their prey. Most plant eaters walked on four feet to better carry their heavy bodies. Some plant eaters could balance on two feet for a short time.",
  "Snakes and lizards shed their skin when they grow. Researchers believe that dinosaurs may have done the same.",
  "Some dinosaurs may have had colorful skin, but scientists don’t know for sure. It’s likely that most dinosaurs had green and brown scales to help them hide among trees and plants.",
  "Tyrannosaurus rex had huge back legs, but its tiny front legs were not much longer than human arms.",
  "While dinosaurs had the same set of leg bones, some had feet like a rhinoceros, elephant, bird, or a pig. The biggest footprints ever found were 3 feet (1 m) across and 4 feet long. Millipedes have more legs than any other animal—up to 750.",
  "Dinosaurs often swallowed large rocks. These rocks stayed in the stomach and helped them grind up food.",
  "Tyrannosaurus rex ate up to 22 tons of meat a year. It had jagged teeth 6 inches (15 cm) long. It couldn’t chew, so it swallowed its food in large chunks.",
  "Deinosuchus was a huge prehistoric crocodile. It most likely had the strongest bite out of any dinosaur, including Tyrannosaurus rex. It weighed eight times as much as today’s crocodile.",
  "Corythosaurus had a big, hollow crest connected to its nose. The crest worked like an echo chamber, letting it make a loud blast of noise.",
  "Sauropods were the tallest animals that ever lived. Some were more than twice the height of a giraffe.",
  "Struthiomimus (“ostrich mimic”), as well as other small hunters, made high-pitched, screechy noises similar to an ostrich.",
  "Parasaurolophus had a crest that looked like half of a trombone. The male’s crest was up to 6 feet (1.8 m) long, which was the biggest out of all the dinosaurs.",
  "Some scientists believe that Tyrannosaurus rex may have been able to run as fast as 18 mph (28 km/h). Other scientists believe it could not run at all because it was so big.",
  "Slim dinosaurs such as Compsognathus and Ornithomimus were among the fastest dinosaurs. However, the cheetah can run faster than any dinosaur that existed.",
  "Dinosaurs that could run on two legs were called bipeds.",
  "In the 1993 movie Jurassic Park, the sound of the T-Rex's footsteps was the sound of cut sequoias crashing to the ground.",
  "Dinosaurs had different self-defense mechanisms. Some, like meat eaters, had sharp teeth. Plant eaters had long horns or sharp spikes. Other dinosaurs were covered in bony plates.",
  "It is estimated that trillions of dinosaur eggs were laid during the Mesozoic era, though fossilized eggs containing embryos are rare.",
  "All dinosaurs laid eggs. About 40 kinds of dinosaur eggs have been discovered.",
  "Modern birds and reptiles have a single body opening for urination, defecation, and reproduction: a cloaca (Latin for “sewer”). Paleontologists believe that dinosaurs were similarly designed and reproduced by pressing their cloacas together in a “cloacal kiss.” Additionally, some dinosaurs may have had a penis like some birds do or other “intromittent organs” like crocodiles. Paleontologists believe a Tyrannosaurus rex male reproductive organ might have been up to 12 feet in length.",
  "Like birds and reptiles today, dinosaurs built nests and laid eggs. Some even fed and protected their babies.",
  "Plant-eating dinosaurs often lived together for protection, like herding animals today do. The herds ranged from just a few adults and their young to thousands of animals.",
  "Sauropods (“Lizard-Footed”) could travel many miles a day on their huge legs. Their fossilized “trackways” or “superhighways” can still be seen today.",
  "The Megalodon was the biggest prehistoric fish. It looked like a shark, though it was three times bigger.",
  "Dinosaurs that lived near water often left the best fossils.",
  "Many scientists believe that birds are dinosaurs and, therefore, dinosaurs are not actually extinct.",
  "The biggest hunter was the Spinosaurus (“spine lizard”). It was up to 49 feet (15 m) long.",
  "The biggest plant eater was the Argentinosaurus. It was up to 98 feet (30 m) long.",
  "The tallest plant eater was the Brachiosaurus (Giraffatitan brancai). Its head was up to 39 feet (12 m) off the ground.",
  "The dinosaur with the thickest skull was the Pachycephalosaurus. Its skull grew up to 8 inches (20 cm) thick.",
  "The Pentaceratops had the biggest skull at 10 feet (3 m) long.",
  "The toothiest dinosaur was the hadrosaurs. It could have over 1,000 teeth and it continually grew new ones.",
  "The biggest flying reptile was the Quetzalcoatlus. It had a wingspan up to 39 feet (12 m).",
  "The dinosaur with the longest claws was the Therizinosaurus (“reaping lizard”). Its claws were up to 3 feet (1 m) long.",
  "The tallest hunter was the Deinocheirus (“horrible hand”). Its head was up to 20 feet (6 m) off the ground.",
  "The fastest dinosaur was the Ornithomimus. It could run up to 43½ mph (70 km/h).",
  "The largest mounted dinosaur skeleton to be exhibited in a museum is a Brachiosaurus.",
  "Stegosaurus had huge upright plates on its back that could grow as large as 30 inches. While scientists do not fully understand the function of these massive plates, they speculate that the stegosaurus could control its body temperature by regulating blood flow through them. A stegosaurus may have also been able to control its skin color this way, to either attract a mate or scare predators. Scientists call this color change “blushing.”",
  "The smallest fully grown dinosaur fossil is Lesothosaurus (“Lizard from Lesotho”). It is only the size of chicken. Smaller fossils have been found, but they are of baby dinosaurs.",
  "The smallest dinosaur egg ever found was only 3 centimeters long and weighed 75 grams. It is not known what kind of species it came from. The largest dinosaur eggs ever found belong to a meat eater in Asia called segnosaurus (“slow lizard”). The eggs are around 19 inches long.",
  "The smartest dinosaur was probably the Troodon (“tooth that wounds”). It had a brain the size of a mammal or bird today. It also had grasping hands and stereoscopic vision.",
  "The first known American dinosaur was discovered in 1858 in the marl pits in Haddonfield, New Jersey. Although other fossils were previously found, they were not correctly identified as dinosaur fossils.",
  "There was such fierce rivalry between paleontologists Edward Cope and Othniel Marsh to find new dinosaurs fossils that they spawned what became known as the Bone Wars. The fight lasted for over 30 years. Marsh is said to have “won” the wars, in part because he found more fossils and he was better funded.",
  "Paleontologists are not perfect. For example, Gideon Mantell (1790-1852) put Iguanodon’s thumb claw on top of its nose. It stayed that way for 40 years. Edward Cope (1840-1897) reconstructed Elasmosaurus (“thin plate”) with its head on the end of its tail. Until recently, Apatosaurus (or Brontosaurus) appeared in museums with the head of Camarasaurus (“chambered lizard”).",
  "Current dinosaur fossil “hot spots” include South America (particularly Argentina) and China, where several feathered dinosaurs have been found.",
  "Dinosaur names are not always static. For example, when paleontologist Othniel C. Marsh first discovered the bones of a giant sauropod, he named it Apatosaurus. When he discovered similar but larger bones a little later, he named it Brontosaurus. However, what Marsh thought were Brontosaurus bones were actually adult Apatosaurus bones, so later scientists decided to change “Brontosaurus” back to “Apatosaurus.”",
  "Scientists can guess how fast a dinosaur walked or ran by looking at the gaps between its footprints.",
  "Ichthyosaur babies were born tail-first. Th they had been born head first, they would have drowned before they could reach the water's surface to take their first breath.",
  "Some pterosaurs had fur on their bodies to keep them warm.",
  "The oldest known dinosaur is Saltopus. A small carnivore, this dinosaur lived over 245 million years ago.",
  "Dinosaurs lived during a period of Earth’s history called the Mesozoic (“middle life”) Era. They lived during all three periods of this era: the Triassic, Jurassic, and Cretaceous.",
  'In 1824 Reverend William Buckland was the first person to name a dinosaur. He named it Megalosaurus, which means "great lizard."',
];

export default facts;

export function randomDinoFact() {
  return facts[Math.floor(Math.random() * facts.length)];
}
